### ISSUE TITLE
Non-negative solutions

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/DiffEqCallbacks.jl#12]
Hi!

Lately I had to deal with some biological dynamical systems (ODEs and DDEs) for which the positive cone is positively invariant, i.e. given positive initial conditions (some) components of the solution remain positive for all finite time. Nevertheless, I had difficulties to retrieve strictly positive numerical solutions of the corresponding differential equations without manually forcing small stepsizes. However, since I want to estimate parameters of these systems as well, and thus would like to use "cheap", i.e. preferably large, step sizes without much manual adjustment I discovered both https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/125 which discusses the implementation of `isoutofdomain` and afterwards a paper about ["Non-negative Solutions of ODEs" by L.F. Shampine et al.](http://www.radford.edu/~thompson/vodef90web/problems/demosnodislin/Demos_MOL/DemoPolymer/nonnegative.pdf) whose results and discussions [apparently are used by MATLAB](https://www.mathworks.com/help/matlab/math/nonnegative-ode-solution.html).

Since my system was not defined outside of the positive cone, I did not succeed in calculating a solution using `isoutofdomain` immediately and started to study the publication mentioned above. I tried to implement the described procedure using a callback. Shortly, it is as follows:

- "a step is accepted only if it passes the usual error test [on the local truncation error] and satisfies the constraints to within the absolute error tolerance"
- "it is not clear how to adjust the step size when a step fails because of the second error estimate since f is generally not smooth at the constraint, so we simply halve the step size then"
- "if a constraint is violated by a component of an accepted approximate solution, the component is projected to zero"

My first try of a callback that follows these principles can be seen [here](https://github.com/devmotion/DiffEqCallbacks.jl/tree/nonnegative). I was a bit confused about the exact order and mechanism with which changes of `u` and `dt` propagate to the solution, and whether I use the interpolant of the integrator correctly to determine if halving of the step size is necessary. Moreover, following Shampine et al. I just halved step sizes and did not use `qmin` and `facmin`, as mentioned in https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/125.

However, according to Shampine et al. another "key idea is to redefine the differential equations outside the feasible region", i.e. "if a component y<sub>j</sub> that is required to be non-negative is passed to the procedure for evaluating f(t, y), the procedure is to return max(0, f<sub>j</sub>(t, y)) instead of f<sub>j</sub>(t, y)". Redefining/extending my system in that way I could also calculate positive numerical solutions using `isoutofdomain`. However, in my case this solution was worse than the callback solution, as the following two figures (callback solution above, `ìsoutofdomain` solution below) of the third component of two naive solutions (method of steps with Tsit5, no further adjustments) of my DDE system show:

![figure_1](https://user-images.githubusercontent.com/26102/27762047-ad9a5d36-5e69-11e7-9eb5-0036cf86aaf0.png)

![figure_2](https://user-images.githubusercontent.com/26102/27762049-bce1d1fc-5e69-11e7-9146-fe5514b664f5.png)

I also reproduced the "absolute value example" from [MATLAB](https://www.mathworks.com/help/matlab/math/nonnegative-ode-solution.html) and implemented it in [a test file](https://github.com/devmotion/DiffEqCallbacks.jl/blob/nonnegative/test/nonnegative_tests.jl). Similar to MATLAB, the non-negative solution fits the analytical solution a lot better, which can be seen in the error measurements:
```julia
julia> naive_sol_absval.errors
Dict{Symbol,Float64} with 3 entries:
  :l∞    => 90365.6
  :final => 90365.6
  :l2    => 13056.6
julia> length(naive_sol_absval.t)
120
julia> nonneg_sol_absval.errors
Dict{Symbol,Float64} with 3 entries:
  :l∞    => 9.87728e-5
  :final => 4.24835e-18
  :l2    => 4.40637e-5
julia> length(nonneg_sol_absval.t)
47
```
I calculated a solution with `isoutofdomain`, too:
```julia
julia> outofdomain_sol_absval.errors
Dict{Symbol,Float64} with 3 entries:
  :l∞    => 9.87728e-5
  :final => 4.24707e-18
  :l2    => 3.44259e-5
julia> length(outofdomain_sol_absval.t)
77
```
Apparently in that example the `isoutofdomain` solution fits the analytical solution slightly better. However, the callback solution needs only 2/3 of the number of steps of the `isoutofdomain` solutions for almost equally good error measurements. (BTW I'm a bit confused about the error estimates - shouldn't `:l∞` always be less or equal to `:l2` since ||x||<sub>∞</sub> <= ||x||<sub>2</sub> for every vector x∈R<sup>n</sup>?)

In my impression the callback method does change the step size in a bit more flexible fashion than `isoutofdomain`. Do you think it would be a good idea to add the non-negative callback (or an improved version thereof) to the DiffEqCallbacks.jl package? Or do you prefer improving the current `isoutofdomain` implementation? Does the implementation follow the principles by Shampine et al. in your opinion? I also thought about generalizing the callback implementation similar to `isoutofdomain`, however I did not know whether it is possible to calculate distances and projections to arbitrary sets defined by a given function in a reasonable and fast way.

Sorry about the length of this post, but it would be great to get some feedback on these questions from you!

**Comment by ChrisRackauckas** [comment]
This looks good. For reference, `qmin` is the minimum that a stepsize can be multiplied by which defaults to `0.2` I think. So the difference there is just how much it moves: `isoutofdomain` is doing `1/5` and this does `1/2`. But this does a little more: `isoutofdomain` doesn't do the limiting on the user's values. 
`isoutofdomain` also doesn't use the interpolation: it just rejects the step and reduces the stepsize.
If `isoutofdomain` projected and dropped by `1/2`, that would match Shampine's. `isoutofdomain` can be improved to allow the projection to the boundary, though the projection would require recomputing the solution anyways to get the interpolation completely right.

Your implementation deviates from Shampine's at one point though. You aren't rejecting the solution, rather you are interpolating back. If the solution is well-behaved near the boundary, your solution would be faster. If negativity destroys stuff easily, then this solution will not be well-behaved because the interpolation will be affected. So `isoutofdomain` is a little safer and could be improved by allowing a projection, but 

https://github.com/devmotion/DiffEqCallbacks.jl/blob/nonnegative/src/nonnegative.jl#L27

This check can happen before 

https://github.com/devmotion/DiffEqCallbacks.jl/blob/nonnegative/src/nonnegative.jl#L10

so that way you don't have to re-interpolate

https://github.com/devmotion/DiffEqCallbacks.jl/blob/nonnegative/src/nonnegative.jl#L21

For the projection part, it will "mess up the interpolation", but that only happens if it goes negative but not by more than the absolute tolerance, so it should be fine.

As for the pictures, `y2` are the stepping points, right? It's just the interpolation for `isoutofdomain` that goes non-negative? If so, that's a slightly wild solution! But yeah, I think these two separate methods act very differently and this callback would complement the existing tools well. Nice stuff: I never knew Shampine looked into this (I should've just asked him :))

>BTW I'm a bit confused about the error estimates - shouldn't :l∞ always be less or equal to :l2 since ||x||∞ <= ||x||2 for every vector x∈Rn?

It's an averaged L2. Otherwise it would just grow by having more points sometimes.

**Comment by devmotion** [comment]
Thanks for your answer!

To the first part: Yes, that's how I understood it already. I thought Shampine also halves step sizes iteratively, but maybe I just misread that one. But yeah, I see your point now - to match Shampine one should rather recalculate the step with halved step size instead of using the interpolation.

Yes, `y2` are the stepping points. So indeed it's only the interpolation for `isoutofdomain` that goes negative. By the way, I could achieve a lot better results by using the `AutoAbstol` callback as well (or, of course, by manually adjusting the absolute tolerances).

**Comment by ChrisRackauckas** [comment]
>To the first part: Yes, that's how I understood it already. I thought Shampine also halves step sizes iteratively, but maybe I just misread that one. But yeah, I see your point now - to match Shampine one should rather recalculate the step with halved step size instead of using the interpolation.

But if the equation is "well-behaved", the interpolation will be much faster so you might as well do it. You might as well just interpolate back to the root of where it's 0, and continue from there. That's a cheap calculation.

**Comment by ChrisRackauckas** [comment]
I think the interpolation one is well worth having because, on applicable problems, it'll be a super cheap and efficient way to handle it. Feel free to turn it into a PR.

**Comment by ChrisRackauckas** [comment]
I believe we can call this complete?

**Comment by devmotion** [comment]
So do I 👍
