### ISSUE TITLE
Performance improvements to TerminateSteadyState

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqCallbacks.jl#34]
A few things track from @AleMorales #33 : 

https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/blob/master/src/terminatesteadystate.jl#L6

The interpolation could make use of a cache variable (but then needs to make sure it's not a number or static array).

https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/blob/master/src/terminatesteadystate.jl#L7

These have a temporary in them and instead should use a generator

https://github.com/JuliaDiffEq/DiffEqCallbacks.jl/blob/master/src/terminatesteadystate.jl#L8

For a `DiscreteCallback` that's just `integrator.u` (missed that before).

Since this is likely not going to be a real performance hog, it's not a priority to change but those should get done sooner or later.

**Comment by AleMorales** [comment]
Some further thoughts on performance improvements (could try to implement soonish if the design is reasonable...):

The generator inside `any` should be different when `reltol` and/or `abstol` are scalars or collections/arrays. Maybe use `length` to branch to the right code?

Whether to use a cache or not should depend on mutability of `du` rather than specific types. Another branch is then possible with `isimmutable` (either the one from Base or one that works statistically on `uType` from `integrator`).

Branchless code maybe possible by using dispatch (assuming all checks can be done at compile time) but I wonder if it is worth it.

**Comment by ChrisRackauckas** [comment]
>Whether to use a cache or not should depend on mutability of du rather than specific types. Another branch is then possible with isimmutable (either the one from Base or one that works statistically on uType from integrator). Branchless code maybe possible by using dispatch (assuming all checks can be done at compile time) but I wonder if it is worth it.

Branching on type information is computed at compile-time, so that's fine. `isimmutable` is not at compile time though (and it's a little slow). It will give incorrect results too, since `Adjoint` is an immutable wrapper around a mutable array, so it will declare that kind of stuff immutable. There's no good answer for that in general in Julia right now, which is why I single out what's important (until we get a trait for this).

**Comment by AleMorales** [comment]
OK, I understand now. In terms of design I think it would still be useful to define our own function (on type, not value). Instead trying to check mutability, it returns `true` (or `Val{true}`?) by default and then we can define methods for the types like `StaticArray` or `Number`. This would give the user the option to override the default behavior.

But I am wondering, why not assume immutability by default rather than the other way around? To me it sounds like a safer option against future data types we are not aware of. But maybe it is not so common to use immutable types in differential equations (I never have)?

**Comment by ChrisRackauckas** [comment]
>But maybe it is not so common to use immutable types in differential equations (I never have)?

Yeah, that's really it. The only real reason to use immutable types are because you're using numbers or static arrays. Any other time you probably want to use mutability. So, at least until we have the trait, it's at least a good heuristic.

**Comment by ChrisRackauckas** [comment]
Nice work!
